# Generated by Django 5.2.4 on 2025-08-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_stripe_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="postal_code",
        ),
    ]
